#
## ??????
#spring:
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    druid:
#      master:
#        url: jdbc:mysql://localhost:6033/ehome?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
#        username: yanfa_user
#        password: Lu1Be8)>pA
#      slave:
#        enable: true
#        url: jdbc:mysql://localhost:6033/ehome?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
#        username: yanfa_user
#        password: Lu1Be8)>pA
#      # ?????
#      initialSize: 5
#      # ???????
#      minIdle: 5
#      # ???????
#      maxActive: 25
#      # ?????????????
#      maxWait: 300000
#      # ???????????????????????????????
#      timeBetweenEvictionRunsMillis: 60000
#      # ??????????????????????
#      minEvictableIdleTimeMillis: 300000
#      # ??????????????????????
#      maxEvictableIdleTimeMillis: 900000
#      validationQuery: SELECT 1 FROM DUAL
#      testWhileIdle: true
#      testOnBorrow: false
#      testOnReturn: false


# ??????
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      master:
        url: jdbc:mysql://localhost:3306/vhr?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
        username: root
        password: 12345678

      # ?????
      initialSize: 5
      # ???????
      minIdle: 5
      # ???????
      maxActive: 25
      # ?????????????
      maxWait: 300000
      # ???????????????????????????????
      timeBetweenEvictionRunsMillis: 60000
      # ??????????????????????
      minEvictableIdleTimeMillis: 300000
      # ??????????????????????
      maxEvictableIdleTimeMillis: 900000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.demo.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl